# Generated by Django 6.0.1 on 2026-01-22 22:26

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilStagiaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='stagiaires/photos/')),
                ('telephone', models.CharField(blank=True, max_length=20)),
                ('date_naissance', models.DateField(blank=True, null=True)),
                ('adresse', models.TextField(blank=True)),
                ('ville', models.CharField(blank=True, max_length=100)),
                ('code_postal', models.CharField(blank=True, max_length=10)),
                ('pays', models.CharField(default='Bénin', max_length=100)),
                ('date_debut_stage', models.DateField()),
                ('date_fin_stage', models.DateField()),
                ('etablissement', models.CharField(help_text="École ou université d'origine", max_length=200)),
                ('diplome_prepare', models.CharField(blank=True, max_length=200)),
                ('niveau_etude', models.CharField(blank=True, max_length=100)),
                ('domaine_specialisation', models.CharField(blank=True, max_length=200)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('inactif', 'Inactif'), ('termine', 'Terminé'), ('suspendu', 'Suspendu')], default='actif', max_length=20)),
                ('niveau_competence', models.CharField(choices=[('debutant', 'Débutant'), ('intermediaire', 'Intermédiaire'), ('avance', 'Avancé')], default='debutant', max_length=20)),
                ('taux_horaire', models.DecimalField(decimal_places=2, default=6.69, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('heures_hebdomadaires', models.PositiveIntegerField(default=35, help_text="Nombre d'heures par semaine")),
                ('competences', models.TextField(blank=True, help_text='Compétences du stagiaire (séparées par des virgules)')),
                ('objectifs_stage', models.TextField(blank=True, help_text='Objectifs à atteindre pendant le stage')),
                ('notes_internes', models.TextField(blank=True, help_text='Notes internes sur le stagiaire')),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('tuteur', models.ForeignKey(blank=True, help_text='Responsable qui supervise le stagiaire', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stagiaires_supervises', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profil_stagiaire', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Stagiaire',
                'verbose_name_plural': 'Profils Stagiaires',
                'ordering': ['-date_debut_stage'],
            },
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_evaluation', models.CharField(choices=[('hebdomadaire', 'Hebdomadaire'), ('mensuelle', 'Mensuelle'), ('trimestrielle', 'Trimestrielle'), ('finale', 'Finale')], max_length=20)),
                ('date_evaluation', models.DateField(default=django.utils.timezone.now)),
                ('competence_technique', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('qualite_travail', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('autonomie', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('communication', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('respect_delais', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('points_forts', models.TextField(blank=True)),
                ('points_amelioration', models.TextField(blank=True)),
                ('commentaire_general', models.TextField(blank=True)),
                ('objectifs_futurs', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('evaluateur', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='evaluations_donnees', to=settings.AUTH_USER_MODEL)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluations', to='objectifs.profilstagiaire')),
            ],
            options={
                'verbose_name': 'Évaluation',
                'verbose_name_plural': 'Évaluations',
                'ordering': ['-date_evaluation'],
            },
        ),
        migrations.CreateModel(
            name='SalaireMensuel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mois', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('annee', models.PositiveIntegerField()),
                ('heures_totales', models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ('salaire_brut', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('deductions', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('salaire_net', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('est_paye', models.BooleanField(default=False)),
                ('date_paiement', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salaires_mensuels', to='objectifs.profilstagiaire')),
            ],
            options={
                'verbose_name': 'Salaire Mensuel',
                'verbose_name_plural': 'Salaires Mensuels',
                'ordering': ['-annee', '-mois'],
                'unique_together': {('stagiaire', 'mois', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Semaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_semaine', models.PositiveIntegerField()),
                ('annee', models.PositiveIntegerField()),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('heures_totales', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('nombre_taches', models.PositiveIntegerField(default=0)),
                ('taches_completees', models.PositiveIntegerField(default=0)),
                ('salaire_calcule', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('commentaire_stagiaire', models.TextField(blank=True)),
                ('commentaire_tuteur', models.TextField(blank=True)),
                ('evaluation_tuteur', models.PositiveIntegerField(blank=True, help_text='Évaluation sur 5', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semaines', to='objectifs.profilstagiaire')),
            ],
            options={
                'verbose_name': 'Semaine',
                'verbose_name_plural': 'Semaines',
                'ordering': ['-annee', '-numero_semaine'],
                'indexes': [models.Index(fields=['stagiaire', 'annee', 'numero_semaine'], name='objectifs_s_stagiai_2b5538_idx')],
                'unique_together': {('stagiaire', 'numero_semaine', 'annee')},
            },
        ),
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('jour_semaine', models.CharField(choices=[('lundi', 'Lundi'), ('mardi', 'Mardi'), ('mercredi', 'Mercredi'), ('jeudi', 'Jeudi'), ('vendredi', 'Vendredi'), ('samedi', 'Samedi')], max_length=20)),
                ('priorite', models.CharField(choices=[('basse', 'Basse'), ('moyenne', 'Moyenne'), ('haute', 'Haute'), ('urgente', 'Urgente')], default='moyenne', max_length=20)),
                ('heures_estimees', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.1)])),
                ('heures_effectuees', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)])),
                ('semaine_numero', models.PositiveIntegerField(help_text="Numéro de la semaine dans l'année")),
                ('annee', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_modification', models.DateTimeField(auto_now=True)),
                ('date_completion', models.DateTimeField(blank=True, null=True)),
                ('est_terminee', models.BooleanField(default=False)),
                ('remarques', models.TextField(blank=True)),
                ('stagiaire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taches', to='objectifs.profilstagiaire')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['annee', 'semaine_numero', 'jour_semaine', '-priorite'],
                'indexes': [models.Index(fields=['stagiaire', 'semaine_numero', 'annee'], name='objectifs_t_stagiai_c9c4ac_idx'), models.Index(fields=['est_terminee'], name='objectifs_t_est_ter_e36f59_idx')],
            },
        ),
    ]
